import { useEffect, useState, useRef } from "react";
import { getCycles, getAnalysis } from "../api";

export default function Report() {
  const [cycles, setCycles]     = useState([]);
  const [analysis, setAnalysis] = useState(null);
  const ref = useRef();

  useEffect(() => {
    getCycles().then(setCycles);
    getAnalysis().then(setAnalysis);
  }, []);

  const exportPDF = async () => {
    const html2pdf = (await import("html2pdf.js")).default;
    html2pdf(ref.current, {
      margin: 10,
      filename: "lunara-health-report.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    });
  };

  return (
    <div className="max-w-2xl mx-auto px-6 py-10 space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-semibold text-purple-100">Health report</h1>
        <button onClick={exportPDF}
          className="bg-teal-700 hover:bg-teal-600 px-5 py-2 rounded-xl text-sm text-white font-medium transition">
          Export PDF
        </button>
      </div>

      <div ref={ref} className="bg-[#1a1030] rounded-2xl p-8 space-y-6 text-purple-100">
        <div className="border-b border-purple-800/30 pb-4">
          <h2 className="text-xl font-semibold text-purple-200">Lunara — Health Report</h2>
          <p className="text-xs text-purple-400 mt-1">Generated {new Date().toDateString()}</p>
        </div>

        {analysis && (
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div><p className="text-purple-400">Total cycles</p><p className="font-medium">{analysis.total_cycles}</p></div>
            <div><p className="text-purple-400">Avg cycle length</p><p className="font-medium">{analysis.avg_length} days</p></div>
            <div><p className="text-purple-400">PCOD risk score</p><p className="font-medium">{analysis.risk_score}/100 ({analysis.risk_level})</p></div>
            <div><p className="text-purple-400">Next cycle</p><p className="font-medium">{analysis.predicted_next}</p></div>
          </div>
        )}

        {analysis?.warnings?.length > 0 && (
          <div>
            <p className="text-sm font-medium text-amber-400 mb-2">Detected irregularities</p>
            <ul className="space-y-1">
              {analysis.warnings.map((w,i) => <li key={i} className="text-xs text-purple-300">• {w}</li>)}
            </ul>
          </div>
        )}

        <div>
          <p className="text-sm font-medium text-purple-300 mb-3">Cycle history</p>
          <table className="w-full text-xs text-purple-300">
            <thead><tr className="text-purple-500 border-b border-purple-800/30">
              <th className="text-left pb-2">Start</th>
              <th className="text-left pb-2">End</th>
              <th className="text-left pb-2">Flow</th>
              <th className="text-left pb-2">Mood</th>
            </tr></thead>
            <tbody>
              {cycles.map(c => (
                <tr key={c.id} className="border-b border-purple-900/20">
                  <td className="py-1.5">{c.start_date}</td>
                  <td>{c.end_date}</td>
                  <td>{c.flow}</td>
                  <td>{c.mood}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="text-xs text-purple-500 border-t border-purple-800/30 pt-4">
          This report is generated by Lunara for informational purposes only. 
          Please consult a qualified gynecologist for medical advice.
        </p>
      </div>
    </div>
  );
}